import React from 'react';

import { Alert, Spinner, Text, VStack } from '@chakra-ui/react';

interface GenerateWordLoadingProps {
  word: string;
}

export const GenerateWordLoading: React.FC<GenerateWordLoadingProps> = ({
  word,
}) => {
  return (
    <VStack
      gap={6}
      align="center"
      justify="center"
      w="full"
      maxW="400px"
      mx="auto"
    >
      <Spinner size="xl" color="blue.500" borderWidth="4px" />
      <VStack gap={2} align="center">
        <Text
          fontSize="lg"
          fontWeight="medium"
          color="gray.700"
          textAlign="center"
        >
          Translating &quot;{word}&quot;...
        </Text>
      </VStack>

      <Alert.Root status="info" w="full">
        <Alert.Indicator />
        <VStack align="start" gap={1} fontSize="sm">
          <Alert.Title>AI-powered translation ✨</Alert.Title>
          <Text>
            This content is generated by AI, so feel free to double-check
            anything that seems off. Not happy with the result? Just hit the
            &quot;Regenerate&quot; button up top!
          </Text>
        </VStack>
      </Alert.Root>
    </VStack>
  );
};
