import type { Metadata } from 'next';
import { Onest } from 'next/font/google';

import { Provider } from '@/chakra/ui/provider';

const onest = Onest({
  subsets: ['latin', 'cyrillic'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Hello World!',
  description: 'Generated by create next app',
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={onest.className}>
        <Provider>{children}</Provider>
      </body>
    </html>
  );
};

export default RootLayout;
