import type { Metadata } from 'next';

import { Provider } from '@/chakra/ui/provider';

export const metadata: Metadata = {
  title: 'Hello World!',
  description: 'Generated by create next app',
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <Provider>{children}</Provider>
      </body>
    </html>
  );
};

export default RootLayout;
