import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import { Provider } from '@/chakra/ui/provider';

const inter = Inter({
  variable: '--font-inter',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.variable}`}>
        <Provider>{children}</Provider>
      </body>
    </html>
  );
};

export default RootLayout;
