name: Perform checks
on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
  workflow_dispatch:

jobs:
  test-and-lint:
    name: Run linters, check build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Set Node version
        uses: actions/setup-node@v2
        with:
          node-version: '20'
      - name: Install Dependencies
        run: npm install
      - name: Run linters
        run: npm run lint
      - name: Verify Build
        run: npm run build
